populate_db: Clean up existing RemoteRealm, RemoteZulipServer objects.
As of 68d44639e486e2c5074db4365047dd081ccbf67c and
0ea682a732e17028a0b8483ecf994554545751b9 we create a default
registration for the dev env "RemoteZulipServer" (and also RemoteRealms
for the dev realms) in populate_db. However these models weren't listed
in clear_database, meaning the state wasn't properly cleaned up at the
start of the command.

Most important, this would manifest in getting:
```
django.db.utils.IntegrityError: duplicate key value violates unique
constraint "zilencer_remotezulipserver_uuid_key"
DETAIL:  Key (uuid)=(......) already exists
```

if you re-run populate_db.