decorator: Fix request.user handling of remote servers.
The refactor in f39414497bd4ec5cb25b83971216ecc2a7913efa didn't
correctly translate the code for managing request.user and
request._email, resulting in requests for the push notification
bouncer being rejected with this exception:

AttributeError: 'AnonymousUser' object has no attribute 'rate_limits'